version: '3.9'

services:
  api :
    build: ./api
    container_name: api
    ports:
    - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
    - "3000:3000"
    depends_on:
    - api

